import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, Menu, X, MoveUpRight, Cpu, Bot, Cloud, ScanLine, CircuitBoard, Sprout, Smartphone, Layers3, Send, ChevronRight, Check, Activity, Zap, Radio, MousePointer2 } from 'lucide-react';
import './styles.css';

const nav = ['Build', 'Devices', 'Software', 'Products', 'Lab', 'AgriTech', 'Training', 'About'];
const tech = ['AI', 'IoT', 'Robotics', 'Embedded Systems', 'Computer Vision', 'Cloud', 'Automation', 'Sensors'];
const stages = [
  ['01','IDEA','Sketch the possibility'],['02','DESIGN','Map the system'],['03','ELECTRONICS','Make it physical'],['04','INTELLIGENCE','Connect the data'],['05','SOFTWARE','Give it a nervous system'],['06','DEPLOY','Put it to work']
];
const products = [
  {name:'BESE26', type:'Digital product', desc:'A focused platform for turning operations into clear, actionable intelligence.', accent:'red'},
  {name:'FarmX', type:'AgriTech system', desc:'Connected tools for farms that need to monitor, automate and grow with confidence.', accent:'green'},
  {name:'FarmX AI', type:'AI application', desc:'Computer vision and intelligent insights for the next generation of farming.', accent:'dark'}
];
const buildOptions = ['Smart Device','Robot','Drone','Automation System','AI Solution','IoT System','Mobile App','Web Platform','Farm Technology'];
const purposeOptions = ['Agriculture','Business','Education','Logistics','Energy','Research','Consumer Technology'];

function Logo({light=false}) { return <a className={`logo ${light?'logo-light':''}`} href="#top" aria-label="SYLUTION home"><span className="logo-mark">S</span><span>SYLUTION</span></a> }
function Reveal({children, className=''}) { return <div className={`reveal ${className}`}>{children}</div> }
function Button({children, dark=false, href='#contact', onClick}) { return <a onClick={onClick} className={`btn ${dark?'btn-dark':''}`} href={href}>{children}<ArrowUpRight size={16}/></a> }
function App(){
  const [loading,setLoading]=useState(true); const [menu,setMenu]=useState(false); const [scroll,setScroll]=useState(0); const [selected,setSelected]=useState('Smart Device'); const [purpose,setPurpose]=useState('Agriculture'); const [sent,setSent]=useState(false);
  useEffect(()=>{const t=setTimeout(()=>setLoading(false),1500); const f=()=>setScroll(window.scrollY/(document.body.scrollHeight-window.innerHeight)*100); window.addEventListener('scroll',f); return()=>{clearTimeout(t);window.removeEventListener('scroll',f)}},[]);
  const systemNodes=useMemo(()=>[selected,'SENSORS','MICROCONTROLLER','IOT CONNECTIVITY',purpose.toUpperCase(),'SYLUTION CLOUD'],[selected,purpose]);
  return <>
    {loading && <div className="preloader"><div className="loader-core"><span className="loader-ring"></span><span className="loader-dot"></span></div><div className="loader-word">SYLUTION</div><div className="loader-status">INITIALIZING THE LAB <span>00—100</span></div><div className="loader-line"><i/></div></div>}
    <div className="progress"><span style={{height:`${scroll}%`}}/><i>{String(Math.round(scroll)).padStart(2,'0')}</i></div>
    <header className="nav"><Logo/><nav>{nav.map((n,i)=><a key={n} href={`#${n.toLowerCase()}`}>{n}<sup>0{i+1}</sup></a>)}</nav><Button href="#contact">Start a project</Button><button className="menu-btn" onClick={()=>setMenu(!menu)} aria-label="menu">{menu?<X/>:<Menu/>}</button></header>
    {menu&&<div className="mobile-menu">{nav.map(n=><a onClick={()=>setMenu(false)} href={`#${n.toLowerCase()}`} key={n}>{n}<ArrowUpRight size={18}/></a>)}<Button href="#contact">Start a project</Button></div>}
    <main id="top">
      <section className="hero section-pad"><div className="hero-grid"></div><div className="hero-copy"><div className="eyebrow"><span className="signal"></span> THE SYLUTION DIGITAL LAB <span className="eyebrow-code">SYS // 001</span></div><h1>We build <em>intelligent</em><br/>technology<br/>for the real world.</h1><p>SYLUTION designs and builds intelligent devices, robotic systems, digital products and agricultural technology powered by AI, IoT, embedded systems and modern software.</p><div className="hero-actions"><Button href="#build">Enter the lab</Button><Button dark href="#contact">Start a project</Button></div><div className="scroll-cue"><span>SCROLL TO EXPLORE</span><div className="scroll-line"></div></div></div><div className="hero-visual"><img src="/assets/hero-core.jpg" alt="SYLUTION intelligent technology core"/><div className="visual-tag tag-a"><span>CORE // ACTIVE</span><b>98.4%</b></div><div className="visual-tag tag-b"><span>NODE 04</span><b>CONNECTED</b></div><div className="orbit orbit-one"></div><div className="orbit orbit-two"></div></div></section>
      <section className="marquee"><div>WE BUILD SYSTEMS THAT <span>SENSE</span> · <span>THINK</span> · <span>CONNECT</span> · <span>ACT</span> · </div></section>
      <section id="build" className="section-pad build-section"><Reveal className="section-intro"><div><div className="eyebrow">01 / FROM IDEA TO PRODUCT</div><h2>From an idea<br/>to a <em>working system.</em></h2></div><p>You bring the problem. We engineer the system. Every project moves through a deliberate loop of design, electronics, intelligence and real-world deployment.</p></Reveal><div className="stage-track">{stages.map((s,i)=><Reveal key={s[1]} className="stage"><div className="stage-num">{s[0]}</div><div className="stage-icon">{[<MousePointer2/>,<Layers3/>,<CircuitBoard/>,<Cpu/>,<Smartphone/>,<Zap/>][i]}</div><h3>{s[1]}</h3><p>{s[2]}</p><span className="stage-arrow">{i<stages.length-1?<ChevronRight/>:<Check/>}</span></Reveal>)}</div></section>
      <section id="devices" className="dark-section section-pad"><Reveal className="split-head"><div><div className="eyebrow light">02 / INTELLIGENT DEVICES & ROBOTICS</div><h2>Machines that<br/><em>sense. think.<br/>connect. act.</em></h2></div><p>We turn intelligence into something tangible: a device, a robot, a drone, a monitoring system, or the machine your problem requires.</p></Reveal><div className="robotic-panel"><img src="/assets/robotics-lab.jpg" alt="Robotic arm assembling intelligent device"/><div className="panel-label"><span className="live-dot"></span> LIVE BUILD / ROBOTICS LAB</div><div className="hotspot hs1"><span></span> SENSORS</div><div className="hotspot hs2"><span></span> ACTUATION</div><div className="hotspot hs3"><span></span> CONTROL</div></div><div className="category-row">{['Smart devices','Robotics','Drones','Automation','Embedded electronics','Custom machinery'].map((x,i)=><div key={x}><span>0{i+1}</span>{x}<ArrowUpRight size={16}/></div>)}</div></section>
      <section id="software" className="section-pad network-section"><Reveal className="section-intro"><div><div className="eyebrow">03 / TECHNOLOGY IS OUR TOOLKIT</div><h2>Products are<br/>the <em>outcome.</em></h2></div><p>AI, IoT, robotics, embedded systems and software are not separate services. They are the stack we use to build things that work.</p></Reveal><div className="network"><div className="network-center"><div className="center-pulse"></div><b>SYLUTION</b><small>BUILD SYSTEM</small></div>{tech.map((t,i)=><button className={`node n${i}`} key={t}><span></span>{t}</button>)}<svg className="network-lines" viewBox="0 0 900 500" preserveAspectRatio="none"><path d="M450 245 L150 80 M450 245 L325 60 M450 245 L600 60 M450 245 L760 125 M450 245 L150 390 M450 245 L340 445 M450 245 L610 445 M450 245 L780 370"/></svg></div></section>
      <section id="products" className="products-section section-pad"><Reveal className="section-intro"><div><div className="eyebrow">04 / PRODUCTS BY SYLUTION</div><h2>Technology<br/>you can <em>own.</em></h2></div><p>Digital products built from the same engineering mindset. Explore the systems already taking shape inside the lab.</p></Reveal><div className="product-grid">{products.map((p,i)=><Reveal className={`product-card ${p.accent}`} key={p.name}><div className="product-top"><span>PRODUCT 0{i+1}</span><ArrowUpRight/></div><div className="mockup"><div className="mockup-bar"><i></i><i></i><i></i></div><div className="mockup-chart"><b>{i===0?'96.8':i===1?'72.4':'88.1'}%</b><small>system health</small><div className="bars"><i/><i/><i/><i/><i/><i/><i/></div></div></div><div className="product-meta"><span>{p.type}</span><h3>{p.name}</h3><p>{p.desc}</p><a href="#contact">View product <ArrowUpRight size={15}/></a></div></Reveal>)}</div></section>
      <section id="lab" className="lab-section section-pad"><div className="lab-copy"><div className="eyebrow light">05 / INSIDE THE SYLUTION LAB</div><h2>See what<br/>we are <em>building.</em></h2><p>Experimental systems, prototypes and production-ready ideas. This is where problems become physical.</p><Button href="#contact">Explore the lab</Button></div><div className="lab-stamp"><span>LAB NOTE</span><b>04</b><small>BUILDING FOR<br/>THE REAL WORLD</small></div></section>
      <section className="configure section-pad"><Reveal className="section-intro"><div><div className="eyebrow">06 / BUILD WITH SYLUTION</div><h2>What should we<br/>build <em>together?</em></h2></div><p>Choose a starting point. We’ll turn your selections into a living system concept.</p></Reveal><div className="configurator"><div className="config-controls"><label>01 / WHAT ARE YOU BUILDING?</label><div className="pills">{buildOptions.map(o=><button className={selected===o?'active':''} onClick={()=>setSelected(o)} key={o}>{o}</button>)}</div><label>02 / WHAT IS THE PURPOSE?</label><div className="pills">{purposeOptions.map(o=><button className={purpose===o?'active':''} onClick={()=>setPurpose(o)} key={o}>{o}</button>)}</div><Button href="#contact">Start this project <Send size={15}/></Button></div><div className="system-view"><div className="system-label">YOUR SYSTEM CONCEPT <span><span className="live-dot"></span> LIVE</span></div><div className="system-stack">{systemNodes.map((n,i)=><React.Fragment key={n}><div className={`system-node node-${i}`}><span>0{i+1}</span>{n}<Activity size={14}/></div>{i<systemNodes.length-1&&<div className="flow"><i></i></div>}</React.Fragment>)}</div></div></div></section>
      <section id="agritech" className="agri-section section-pad"><div className="agri-image"><img src="/assets/agritech.jpg" alt="Smart agriculture with sensors and irrigation"/><div className="agri-readout"><span>FIELD NODE 08</span><b>IRRIGATION / ACTIVE</b><div className="readout-line"><i/></div></div></div><div className="agri-copy"><div className="eyebrow">07 / AGRITECH</div><h2>Technology for<br/><em>modern farming.</em></h2><p>From crops to livestock, SYLUTION builds technology that helps farms monitor, automate and improve real-world operations.</p><div className="agri-list">{['Smart irrigation','Agricultural drones','Farm monitoring','AI agriculture','Livestock technology','Farm machinery'].map((x,i)=><div key={x}><span>0{i+1}</span>{x}<ArrowUpRight size={15}/></div>)}</div></div></section>
      <section id="training" className="training-section section-pad"><div><div className="eyebrow light">08 / TECHNOLOGY TRAINING</div><h2>Learn what<br/>we <em>build.</em></h2><p>Practical technology training from people building real systems. Robotics, AI, IoT, electronics, software and more.</p><Button href="#contact">Explore training</Button></div><div className="training-grid">{['Robotics','Artificial Intelligence','IoT & Sensors','Embedded Systems','Software Development','AgriTech'].map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b><ArrowUpRight/></div>)}</div></section>
      <section id="about" className="about-section section-pad"><Reveal className="section-intro"><div><div className="eyebrow">09 / ABOUT SYLUTION</div><h2>Engineering what<br/>should <em>exist.</em></h2></div><p>We are a deeptech engineering company building intelligent devices, software and agricultural systems from the ground up.</p></Reveal><div className="principles"><div><span>01</span><b>Real problems</b><p>We start with what the world actually needs.</p></div><div><span>02</span><b>Practical engineering</b><p>We design for the field, not only the lab.</p></div><div><span>03</span><b>Intelligent technology</b><p>We use the right stack to make systems smarter.</p></div><div><span>04</span><b>Real impact</b><p>We measure success by what works in the real world.</p></div></div></section>
      <section id="contact" className="contact-section section-pad"><div className="contact-grid"><div><div className="eyebrow light">10 / START A PROJECT</div><h2>Have an idea<br/>that should <em>exist?</em></h2><p>Let’s engineer it.</p><div className="contact-signal"><span></span> SYLUTION // READY TO CONNECT</div></div><form onSubmit={e=>{e.preventDefault();setSent(true)}}>{sent?<div className="success"><Check size={34}/><h3>Signal received.</h3><p>We’ll be in touch when the system is ready to move.</p></div>:<><div className="form-row"><input required placeholder="Your name"/><input required type="email" placeholder="Email address"/></div><input placeholder="Company / organisation"/><select><option>What do you want to build?</option><option>Smart device</option><option>Robotics system</option><option>Software / AI</option><option>AgriTech</option></select><textarea placeholder="Tell us about the problem you want to solve"></textarea><button className="btn btn-light" type="submit">Send project brief <Send size={16}/></button></>}</form></div></section>
    </main>
    <footer><div className="footer-top"><Logo light/><span>BUILT FOR THE REAL WORLD.</span><a href="#top">Back to top <ArrowUpRight size={15}/></a></div><div className="footer-bottom"><span>© 2026 SYLUTION. THE DIGITAL LAB.</span><div><a href="#about">About</a><a href="#contact">Contact</a><a href="#">Privacy</a></div><span className="footer-signal"><i></i> SIGNAL ONLINE</span></div></footer>
  </>
}
createRoot(document.getElementById('root')).render(<App/>);
